version: "3.9"

name: kzw

services:
  backend:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - ./apps/backend:/app
    command: >-
      sh -c "pip install --no-cache-dir -r requirements.txt &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    networks:
      - kzw

  frontend:
    user: "${UID}:${GID}"
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./apps/frontend:/app
    command: >-
      sh -c "npm install && npm run dev -- --port 3000"
    environment:
      - PORT=3000
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - kzw

  # db:
  #   image: postgres:16-alpine
  #   environment:
  #     - POSTGRES_DB=kzw
  #     - POSTGRES_USER=kzw
  #     - POSTGRES_PASSWORD=kzw
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - kzw_pg:/var/lib/postgresql/data
  #   networks:
  #     - kzw

networks:
  kzw:
    driver: bridge

volumes:
  kzw_pg:
